import type { SourceReport } from "../types";

/** Research-order priority — NOT result sort order. */
export const SOURCE_REGISTRY: SourceReport[] = [
  {
    id: "ajet",
    name: "AJet",
    priority: 1,
    status: "inaccessible",
    realPriceVerified: false,
    passengerBaggageReadable: false,
    limitations: ["Doğrudan erişim yeniden denenecek; ENUYGUN VF kapsamı."],
  },
  {
    id: "turkish-airlines",
    name: "Turkish Airlines",
    priority: 2,
    status: "inaccessible",
    realPriceVerified: false,
    passengerBaggageReadable: false,
    limitations: [
      "TKCONNECT NDC partner kimlik ister.",
      "RT iki tek yön toplamı olarak tahmin edilmeyecek.",
    ],
  },
  {
    id: "pegasus",
    name: "Pegasus",
    priority: 3,
    status: "partial",
    realPriceVerified: false,
    passengerBaggageReadable: false,
    limitations: ["Port/status OK; takvim fiyat POST Akamai 403."],
  },
  {
    id: "sunexpress",
    name: "SunExpress",
    priority: 4,
    status: "inaccessible",
    realPriceVerified: false,
    passengerBaggageReadable: false,
    limitations: ["Cloudflare challenge."],
  },
  {
    id: "corendon",
    name: "Corendon",
    priority: 5,
    status: "inaccessible",
    realPriceVerified: false,
    passengerBaggageReadable: false,
    limitations: ["Cloudflare challenge; sezonsal no-flight ≠ erişim hatası."],
  },
  {
    id: "skyscanner",
    name: "Skyscanner TR",
    priority: 6,
    status: "inaccessible",
    realPriceVerified: false,
    passengerBaggageReadable: false,
    limitations: [
      "Partner API key yok; CAPTCHA. SKYSCANNER_API_KEY yolu hazır.",
    ],
  },
  {
    id: "enuygun",
    name: "ENUYGUN",
    priority: 7,
    status: "working",
    realPriceVerified: true,
    passengerBaggageReadable: true,
    limitations: [
      "Resmi MCP — yurt içi + yurt dışı doğrulanmış RT fiyat.",
    ],
  },
  {
    id: "turna",
    name: "Turna",
    priority: 8,
    status: "inaccessible",
    realPriceVerified: false,
    passengerBaggageReadable: false,
    limitations: ["Access Denied / henüz fiyat API yok."],
  },
  {
    id: "obilet",
    name: "Obilet",
    priority: 9,
    status: "partial",
    realPriceVerified: false,
    passengerBaggageReadable: false,
    limitations: ["Ana sayfa 200; fiyat API doğrulanamadı."],
  },
  {
    id: "google-flights",
    name: "Google Flights TR",
    priority: 10,
    status: "not-attempted",
    realPriceVerified: false,
    passengerBaggageReadable: false,
    limitations: ["Takvim ≠ verified booking."],
  },
  {
    id: "kayak",
    name: "KAYAK TR",
    priority: 11,
    status: "not-attempted",
    realPriceVerified: false,
    passengerBaggageReadable: false,
    limitations: ["ToS kontrolü şart."],
  },
];
