import type { SourceReport } from "../types";

/** Research-order priority — NOT result sort order. */
export const SOURCE_REGISTRY: SourceReport[] = [
  {
    id: "pegasus",
    name: "Pegasus",
    priority: 1,
    status: "partial",
    realPriceVerified: false,
    passengerBaggageReadable: false,
    limitations: [
      "web.flypgs.com status/ports/languages okunabiliyor (gzip + X-Platform).",
      "Takvim/fiyat POST (apint/cheapfare/flight-calender-prices) bu ortam IP’sinden Akamai 403.",
      "RT yolcu+bagaj doğrulaması CAPTCHA/bot engeli nedeniyle yapılmadı (bypass yok).",
      "Açık site: https://www.flypgs.com — fiyat için şimdilik ENUYGUN üzerinden PC uçuşları görünür.",
    ],
    lastTestedAt: "2026-09-30T18:44:00Z",
    lastTestRoute: "SAW→AYT takvim POST",
  },
  {
    id: "ajet",
    name: "AJet",
    priority: 2,
    status: "inaccessible",
    realPriceVerified: false,
    passengerBaggageReadable: false,
    limitations: [
      "ajet.com / www.ajet.com bu ortamdan TLS handshake sonrası yanıt vermiyor (timeout).",
      "Resmi API DIJI.TECH / NDC partner kimlik bilgisi gerektiriyor; ücretsiz genel erişim yok.",
      "ENUYGUN sonuçlarında VF (AJet) teklifleri gerçek fiyatla görülebiliyor.",
    ],
    lastTestedAt: "2026-09-30T18:44:00Z",
    lastTestRoute: "www.ajet.com homepage",
  },
  {
    id: "skyscanner",
    name: "Skyscanner TR",
    priority: 3,
    status: "inaccessible",
    realPriceVerified: false,
    passengerBaggageReadable: false,
    limitations: [
      "Öncelikli kaynak; doğrulanmış otomatik fiyat için resmi partner Live Prices API anahtarı gerekir.",
      "Anahtarsız create → 401; site/curl → CAPTCHA (bypass yok). Widget/link-only tamamlanmış sayılmaz.",
      "Tarayıcıda manuel IST→AMS TRY fiyatlar görüldü — uygulama entegrasyonu değil.",
      "Hard dependency değil; ENUYGUN çalışır. SKYSCANNER_API_KEY varsa Live Prices yolu hazır.",
    ],
    lastTestedAt: "2026-09-30T19:25:00Z",
    lastTestRoute: "API 401 + CAPTCHA probe + browser IST→AMS 20–25.10.2026",
  },
  {
    id: "enuygun",
    name: "ENUYGUN",
    priority: 4,
    status: "working",
    realPriceVerified: true,
    passengerBaggageReadable: true,
    limitations: [
      "Resmi MCP: https://mcp.enuygun.com/mcp — flight_search + flight_allocate.",
      "Doğrulandı: İstanbul→Antalya RT 20.10.2026–25.10.2026, TRY fiyat + saat + bagaj + rezervasyon linki.",
      "Uluslararası (örn. İstanbul→Amsterdam) MCP ile aranabilir.",
    ],
    lastTestedAt: "2026-09-30T18:42:00Z",
    lastTestRoute: "İstanbul → Antalya, 20.10.2026–25.10.2026, 1 yetişkin",
  },
  {
    id: "turna",
    name: "Turna",
    priority: 5,
    status: "not-attempted",
    realPriceVerified: false,
    passengerBaggageReadable: false,
    limitations: ["Skyscanner/ENUYGUN sonrası sırada; henüz denenmedi."],
  },
  {
    id: "obilet",
    name: "Obilet",
    priority: 6,
    status: "not-attempted",
    realPriceVerified: false,
    passengerBaggageReadable: false,
    limitations: ["Skyscanner/ENUYGUN sonrası sırada; henüz denenmedi."],
  },
  {
    id: "turkish-airlines",
    name: "Turkish Airlines",
    priority: 7,
    status: "not-attempted",
    realPriceVerified: false,
    passengerBaggageReadable: false,
    limitations: [
      "RT iki tek yön toplamı olarak tahmin edilmeyecek.",
      "Henüz doğrudan entegrasyon denenmedi.",
    ],
  },
  {
    id: "sunexpress",
    name: "SunExpress",
    priority: 8,
    status: "not-attempted",
    realPriceVerified: false,
    passengerBaggageReadable: false,
    limitations: ["TR–Avrupa rotasında öncelik artacak; henüz denenmedi."],
  },
  {
    id: "corendon",
    name: "Corendon",
    priority: 9,
    status: "not-attempted",
    realPriceVerified: false,
    passengerBaggageReadable: false,
    limitations: ["Sezonsal uçuş yokluğu erişim hatası değildir; henüz denenmedi."],
  },
  {
    id: "google-flights",
    name: "Google Flights TR",
    priority: 10,
    status: "not-attempted",
    realPriceVerified: false,
    passengerBaggageReadable: false,
    limitations: [
      "Takvim/keşif için uygun; takvim fiyatı ≠ doğrulanmış rezervasyon teklifi.",
      "Otomatik fiyat okuma uygun değilse yalnızca siteyi aç — link-only tamamlanmış sayılmaz.",
    ],
  },
  {
    id: "kayak",
    name: "KAYAK TR",
    priority: 11,
    status: "not-attempted",
    realPriceVerified: false,
    passengerBaggageReadable: false,
    limitations: ["Otomasyon öncesi ToS kontrolü gerekli."],
  },
];
